# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure('2') do |config|
  config.vm.box = "ubuntu-trusty-64"
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"

  #configure ssh forward agent
  `key_file=~/.ssh/id_rsa && [[ -z $(ssh-add -L | grep $key_file) ]] && ssh-add $key_file`
  config.ssh.forward_agent = true

  config.vm.define :app_server do |node|
    node.vm.network "private_network", ip: "10.0.0.3"

    node.vm.network 'forwarded_port', guest: 80, host: 10080

    id_rsa_ssh_key_pub = File.read(File.join(Dir.home, ".ssh", "id_rsa.pub"))
    node.vm.provision :shell do |s|
      s.path = "bootstrap.sh"
      s.args = "\"#{id_rsa_ssh_key_pub}\""
      s.privileged = false
    end

    node.vm.provider "virtualbox" do |vb|
      vb.name = "od4d-app-server"
      vb.customize ["modifyvm", :id, "--memory", "1024"]
    end
  end

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end
end
